###############################################################################
# Sobre o GitHub Actions                                                      #
# https://docs.github.com/en/actions/learn-github-actions                     #
# https://www.youtube.com/watch?v=TLB5MY9BBa4                                 #
###############################################################################
#
# Padroniza o formato do arquivo composer.json de acordo com o esquema proposto
# pela equipe desenvolvedora do composer.
#
# Motivação: https://localheinz.com/blog/2018/01/15/normalizing-composer.json/
# Esquema: https://getcomposer.org/schema.json

name: Normalização do composer

on:
  workflow_dispatch:
  push:
    paths:
      - 'composer.json'

concurrency:
  group: normaliza-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  normalize:
    runs-on: ubuntu-latest

    name: Normaliza composer.json

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Run
        run: |
          composer require --dev ergebnis/composer-normalize
          composer config allow-plugins.ergebnis/composer-normalize true
          composer normalize

      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'style(composer): normaliza composer.json'
          branch: ${{ github.head_ref }}
